services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./cinspect.db
    depends_on: []

  # db:  <- descomentar na Fase 1 ao migrar para PostgreSQL
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: cinspect
  #     POSTGRES_PASSWORD: cinspect
  #     POSTGRES_DB: cinspect
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
